name: Continuous Integration/Continuous Deployment
on:
 push:
    branches:
     - main 
 workflow_run:
   workflows: ["Continuous Training"]
   branches: [main]
   types:
     - completed
 workflow_dispatch:
   inputs:
     reason:
       description: Why to run this?
       required: false
       default: running CI/CD
jobs:
  ci_cd:
    runs-on: ubuntu-latest
    env:
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
      REGION: ${{ secrets.REGION }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set environment and bring the model
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install dvc[gs]
          export GOOGLE_APPLICATION_CREDENTIALS=$(python utilities/setter.py)
          dvc pull model/model.pkl.dvc -r model-track
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'
      - name: Set up GCLOUD SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
      - name: Configure Docker
        run: |
          gcloud auth configure-docker -q
      - name: Build and Push
        run: |
          docker build . -t $REGISTRY_NAME:$GITHUB_SHA
          sudo -u $USER docker push $REGISTRY_NAME:$GITHUB_SHA
      - name: Deploy to Cloud Run
        run: |
          gcloud run services update $SERVICE_NAME --region=$REGION --image=$REGISTRY_NAME:$GITHUB_SHA